(part "QBA-07+"
    (packageRef "QBA07")
    (interface
        (port "1" (symbPinId 1) (portName "SUM_PORT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GROUND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GROUND_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GROUND_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "50_OHM_TERM_EXTERNAL") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PORT_2_(0°)") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GROUND_4") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GROUND_5") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GROUND_6") (portType INOUT))
        (port "10" (symbPinId 10) (portName "PORT_1_(+90°)") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Mini-Circuits")
    (property "Manufacturer_Part_Number" "QBA-07+")
    (property "Description" "Power Splitter/Combiner, 2 Way-90 50 340 to 680 MHz-1")
    (property "Datasheet_Link" "https://www.minicircuits.com/pdfs/QBA-07.pdf")
    (property "symbolName1" "QBA-07+")
)
